name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true

      # Step 5: Merge all Mochawesome JSON reports
      - name: Merge Mochawesome JSON reports
        run: npm run report:merge

      # Step 6: Generate final HTML report
      - name: Generate HTML report
        run: npm run report:generate

      # Step 7: Send Cypress HTML report via email (attachment)
      - name: Send Cypress HTML report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Cypress Test Report - ${{ github.run_number }}"
          to: jkpatel141@gmail.com;Durgesh.singh9565@yahoo.in
          from: "Cypress CI <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hi Team,

            The latest Cypress test run is complete.  
            Please find attached the detailed HTML report.

            Regards,  
            CI/CD Pipeline
          attachments: cypress/reports/report.html

      # Step 8: Upload Cypress report folder as artifact
      - name: Upload Cypress HTML report
        id: upload-report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports